name: Run Selenium CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Chrome with extra capabilities
        uses: browser-actions/setup-chrome@v1.4.0
        with:
          chrome-version: latest

      - name: Build with Gradle
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew clean test

      - name: Archive test results
        uses: actions/upload-artifact@v4.3.0
        if: always()
        with:
          name: cucumber reports
          path: |
            reports/cucumber-reports.html

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          PERSONAL_TOKEN: ${{ secrets.DEPLOY_SELENIUM }}
          PUBLISH_DIR: report