name: Run JUnit4 and Cucumber Tests with Gradle

# Triger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build and run tests
        run: |
          ./gradlew clean test